"""Human-readable descriptions of each claim category (used by prompts and the UI)."""

CATEGORIES = {
    "guaranteed_returns": {
        "en": "Guaranteed or unrealistic returns",
        "hi": "गारंटीड या बहुत ज़्यादा रिटर्न का वादा",
        "about_en": "Promises of fixed, 'sure', risk-free or very high returns. No market investment can guarantee returns.",
        "about_hi": "पक्के, बिना जोखिम वाले या बहुत ज़्यादा रिटर्न का वादा। बाज़ार में कोई भी निवेश रिटर्न की गारंटी नहीं दे सकता।",
        "prompt": "promises fixed/assured/'sure-shot'/risk-free returns, 'money will double', 'you cannot lose', specific % per day/week/month as an expected outcome",
    },
    "stock_tip": {
        "en": "Specific buy/sell call",
        "hi": "खरीदने-बेचने की टिप",
        "about_en": "Telling viewers to buy or sell a specific security, often with entry, target and stop-loss. Only SEBI-registered RAs/IAs may give such advice.",
        "about_hi": "किसी खास शेयर को खरीदने या बेचने को कहना, अक्सर एंट्री, टारगेट और स्टॉप-लॉस के साथ। ऐसी टिप सिर्फ़ SEBI में रजिस्टर्ड रिसर्च एनालिस्ट या इन्वेस्टमेंट एडवाइज़र ही दे सकते हैं।",
        "prompt": "a concrete recommendation to buy/sell/hold a NAMED stock, option, coin or fund, or entry/target/stop-loss levels for one",
    },
    "price_prediction": {
        "en": "Price prediction / hype",
        "hi": "भाव का अनुमान / हाइप",
        "about_en": "Confident predictions that a stock will double, hit a price or become a 'multibagger'. Nobody can reliably predict prices.",
        "about_hi": "पक्के दावे कि शेयर डबल होगा, किसी कीमत तक जाएगा या 'मल्टीबैगर' बनेगा। शेयर का भाव कहाँ जाएगा, यह पक्के तौर पर कोई नहीं बता सकता।",
        "prompt": "confident forecasts of where a specific price/index will go, 'multibagger', 'rocket', 'will 10x'",
    },
    "urgency_fomo": {
        "en": "Urgency / fear of missing out",
        "hi": "जल्दबाज़ी का दबाव",
        "about_en": "Pressure to act immediately ('last chance', 'before it's too late'). Good decisions are rarely urgent.",
        "about_hi": "'आखिरी मौका', 'देर मत करो' जैसी बातों से तुरंत पैसा लगाने का दबाव। सही फैसले जल्दबाज़ी में नहीं होते।",
        "prompt": "pressure to act right now, 'last chance', 'before it's too late', limited seats/time, fear of missing out",
    },
    "paid_promotion": {
        "en": "Paid promotion / affiliate",
        "hi": "पेड प्रमोशन / रेफ़रल लिंक",
        "about_en": "Sponsored content, referral links or 'open a demat account with my link'. The creator may earn from what they recommend.",
        "about_hi": "स्पॉन्सर्ड वीडियो, रेफ़रल लिंक या 'मेरे लिंक से डीमैट खाता खोलें'। जिस चीज़ की सलाह दी जा रही है, उससे क्रिएटर को कमीशन मिल सकता है।",
        "prompt": "sponsorship, affiliate/referral links or codes, 'open demat account using my link', commissions the creator earns",
    },
    "paid_group": {
        "en": "Paid / Telegram / VIP group",
        "hi": "पेड ग्रुप / टेलीग्राम / VIP",
        "about_en": "Pushing viewers into Telegram/WhatsApp/'premium' groups or paid courses. Many tip-scams start this way.",
        "about_hi": "दर्शकों को टेलीग्राम, व्हाट्सऐप या 'प्रीमियम' ग्रुप या पेड कोर्स में जुड़ने को कहना। टिप्स के नाम पर ज़्यादातर ठगी ऐसे ही शुरू होती है।",
        "prompt": "invitations to Telegram/WhatsApp/VIP/premium groups, paid tips, paid mentorship or courses",
    },
    "registration_claim": {
        "en": "Claims SEBI registration",
        "hi": "SEBI रजिस्ट्रेशन का दावा",
        "about_en": "Claims to be SEBI-registered. Nirikshak checks this against SEBI's public registry.",
        "about_hi": "SEBI में रजिस्टर्ड होने का दावा। निरीक्षक इसे SEBI की सार्वजनिक सूची से मिलाकर देखता है।",
        "prompt": "the speaker claims to be SEBI registered / a registered research analyst or investment adviser, or states an INH/INA number",
    },
    "misleading_claim": {
        "en": "Misleading or cherry-picked claim",
        "hi": "गुमराह करने वाला दावा",
        "about_en": "Showing only winning trades, unverifiable profit screenshots, or presenting a strategy as if it cannot fail.",
        "about_hi": "सिर्फ़ मुनाफे वाले ट्रेड दिखाना, प्रॉफिट के ऐसे स्क्रीनशॉट जिन्हें जाँचा न जा सके, या किसी तरीके को ऐसे बताना जैसे उसमें कभी नुकसान नहीं होगा।",
        "prompt": "showcasing only profits, unverifiable P&L screenshots as proof, claims a strategy 'always works', misrepresenting risk",
    },
    "credential_request": {
        "en": "Asks for OTP, PIN or remote access",
        "hi": "OTP, PIN या फ़ोन का कंट्रोल माँगना",
        "about_en": "No bank, broker, SEBI or depository will ever ask for your OTP, PIN, password, or ask you to install a screen-sharing app like AnyDesk.",
        "about_hi": "कोई भी बैंक, ब्रोकर, SEBI या डिपॉज़िटरी कभी आपका OTP, PIN या पासवर्ड नहीं माँगेगा, न ही AnyDesk जैसा स्क्रीन-शेयरिंग ऐप डलवाएगा।",
        "prompt": "asks the reader to share an OTP, PIN, UPI PIN, password or CVV, or to install a screen-sharing/remote-access app",
    },
    "suspicious_link": {
        "en": "Suspicious link or app download",
        "hi": "संदिग्ध लिंक या ऐप डाउनलोड",
        "about_en": "Fake trading apps (often .apk files) and shortened links are a common way to steal money and data. Install apps only from official app stores.",
        "about_hi": "नकली ट्रेडिंग ऐप (अक्सर .apk फ़ाइल) और छोटे लिंक से पैसे और डेटा चुराए जाते हैं। ऐप सिर्फ़ आधिकारिक ऐप स्टोर से ही डालें।",
        "prompt": "pushes an APK download, an unknown trading app, or a shortened / suspicious link",
    },
    "upfront_payment": {
        "en": "Upfront payment or fee",
        "hi": "पहले पैसे या फ़ीस माँगना",
        "about_en": "Being asked to pay a joining, activation or 'withdrawal' fee, or to send money to a personal UPI ID or QR code, is a classic trap. Registered firms don't collect money this way.",
        "about_hi": "जुड़ने, एक्टिवेशन या 'पैसे निकालने' के लिए फ़ीस माँगना, या किसी निजी UPI ID या QR कोड पर पैसे भेजने को कहना, ठगी का आम तरीका है। रजिस्टर्ड कंपनियाँ ऐसे पैसे नहीं लेतीं।",
        "prompt": "asks for a fee to join, unlock, activate or withdraw, or to send money to a UPI ID / QR / personal account",
    },
    "impersonation": {
        "en": "Pretends to be an official or a known firm",
        "hi": "किसी अधिकारी या जानी-मानी कंपनी होने का दिखावा",
        "about_en": "Scammers pose as SEBI, NSE, a well-known broker or a famous investor, or threaten that your account will be blocked unless you 'update KYC'. Verify through the official website or app only.",
        "about_hi": "ठग खुद को SEBI, NSE, कोई बड़ा ब्रोकर या मशहूर निवेशक बताते हैं, या धमकी देते हैं कि 'KYC अपडेट' नहीं किया तो खाता बंद हो जाएगा। सिर्फ़ आधिकारिक वेबसाइट या ऐप से ही जाँचें।",
        "prompt": "claims to be from SEBI, NSE, BSE, a broker, bank or famous investor, or threatens account blocking / KYC expiry",
    },
}
